apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-detection.fullname" . }}
  labels:
    {{- include "fraud-detection.labels" . | nindent 4 }}
data:
  FRAUD_RULES_LARGE_AMOUNT_THRESHOLD: {{ .Values.fraudRules.largeAmountThreshold | quote }}
  FRAUD_RULES_SUSPICIOUS_ACCOUNTS: {{ .Values.fraudRules.suspiciousAccounts | quote }}
  FRAUD_RULES_RAPID_FIRE_MAX_PER_MINUTE: {{ .Values.fraudRules.rapidFireMaxPerMinute | quote }}

