apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transaction-producer.fullname" . }}
  labels:
    {{- include "transaction-producer.labels" . | nindent 4 }}
data:
  TRANSACTION_AUTO_GENERATE_ENABLED: {{ .Values.autoGenerate.enabled | quote }}

