# Values file for GCP test environment

fraud-detection:
  replicaCount: 2
  image:
    tag: "latest"
  cloudProvider: gcp
  gcp:
    projectId: fraud-detection-project-test
    pubsub:
      subscriptionName: fraud-detection-sub-test
  serviceAccount:
    create: true
    annotations:
      # iam.gke.io/gcp-service-account: fraud-detection-test@PROJECT_ID.iam.gserviceaccount.com
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

transaction-producer:
  replicaCount: 1
  image:
    tag: "latest"
  cloudProvider: gcp
  gcp:
    projectId: fraud-detection-project-test
    pubsub:
      topicName: fraud-detection-topic-test
  autoGenerate:
    enabled: false
  serviceAccount:
    create: true
    annotations:
      # iam.gke.io/gcp-service-account: transaction-producer-test@PROJECT_ID.iam.gserviceaccount.com

